# Generated by Django 5.0.4 on 2026-01-19 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del cliente', max_length=200)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento del cliente')),
                ('edad', models.IntegerField(help_text='Edad del cliente (calculada automáticamente)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('nacionalidad', models.CharField(blank=True, help_text='Nacionalidad del cliente', max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección del cliente', max_length=500, null=True)),
                ('email', models.EmailField(help_text='Correo electrónico del cliente', max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del cliente', max_length=20, null=True)),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDICO', 'Jurídico')], default='NATURAL', help_text='Tipo de persona', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(blank=True, help_text='Banco asociado al cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='bancos.banco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nombre_completo'],
                'indexes': [models.Index(fields=['email'], name='clientes_email_fb2cd6_idx'), models.Index(fields=['tipo_persona'], name='clientes_tipo_pe_2429dd_idx')],
            },
        ),
    ]
