# Generated by Django 5.0.4

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.IntegerField(
                help_text='Edad del cliente (calculada automáticamente, mínimo 18 años)',
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(99)
                ]
            ),
        ),
    ]
