# Generated by Django 5.0.4 on 2026-01-19 20:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bancos', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción del crédito', max_length=500)),
                ('pago_minimo', models.DecimalField(decimal_places=2, help_text='Pago mínimo del crédito', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pago_maximo', models.DecimalField(decimal_places=2, help_text='Pago máximo del crédito', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('plazo_meses', models.IntegerField(help_text='Plazo del crédito en meses', validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha de registro del crédito')),
                ('tipo_credito', models.CharField(choices=[('AUTOMOTRIZ', 'Automotriz'), ('HIPOTECARIO', 'Hipotecario'), ('COMERCIAL', 'Comercial')], help_text='Tipo de crédito', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(help_text='Banco que otorga el crédito', on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='bancos.banco')),
                ('cliente', models.ForeignKey(help_text='Cliente al que pertenece el crédito', on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'db_table': 'creditos',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['cliente'], name='creditos_cliente_2266be_idx'), models.Index(fields=['banco'], name='creditos_banco_i_592c5b_idx'), models.Index(fields=['fecha_registro'], name='creditos_fecha_r_2cb72f_idx'), models.Index(fields=['tipo_credito'], name='creditos_tipo_cr_82d2b0_idx')],
            },
        ),
    ]
