# Generated by Django 5.0.4 on 2026-01-20 17:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_credito_tasa_interes_cuota_mensual_monto_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto total del crédito (importe otorgado)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
    ]
