# Generated by Django 5.0.4 on 2026-01-19 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del banco', max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('tipo', models.CharField(choices=[('PRIVADO', 'Privado'), ('GOBIERNO', 'Gobierno')], help_text='Tipo de banco', max_length=20)),
                ('direccion', models.CharField(blank=True, help_text='Dirección del banco', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
                'ordering': ['nombre'],
            },
        ),
    ]
