# Generated by Django 5.0.4 on 2026-01-20 15:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bancos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código único del banco', max_length=50, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='banco',
            name='email',
            field=models.EmailField(blank=True, help_text='Email de contacto del banco', max_length=255, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='banco',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', help_text='Estado del banco', max_length=20),
        ),
        migrations.AddField(
            model_name='banco',
            name='monto_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo de crédito (MXN)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='banco',
            name='monto_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto mínimo de crédito (MXN)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='banco',
            name='plazo_maximo',
            field=models.PositiveIntegerField(blank=True, help_text='Plazo máximo en meses', null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='plazo_minimo',
            field=models.PositiveIntegerField(blank=True, help_text='Plazo mínimo en meses', null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='Sitio web del banco', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='tasa_interes_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de interés máxima anual (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='banco',
            name='tasa_interes_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de interés mínima anual (%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='banco',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto del banco', max_length=50, null=True),
        ),
    ]
